<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
<meta name="theme-color" content="#222">
<meta name="generator" content="Hexo 6.3.0">
  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">


<link rel="stylesheet" href="/lib/font-awesome/css/all.min.css">

<script id="hexo-configurations">
    var NexT = window.NexT || {};
    var CONFIG = {"hostname":"yoursite.com","root":"/","scheme":"Mist","version":"7.8.0","exturl":false,"sidebar":{"position":"left","display":"post","padding":18,"offset":12,"onmobile":false},"copycode":{"enable":false,"show_result":false,"style":null},"back2top":{"enable":true,"sidebar":false,"scrollpercent":false},"bookmark":{"enable":false,"color":"#222","save":"auto"},"fancybox":false,"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"algolia":{"hits":{"per_page":10},"labels":{"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}},"localsearch":{"enable":true,"trigger":"auto","top_n_per_article":1,"unescape":false,"preload":false},"motion":{"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},"path":"search.json"};
  </script>

  <meta name="description" content="之前在学习工作中虽然一直在用 Java 的异常处理，但一直都处于仅仅了解简单用法的表面基础上。最近趁有空进一步深入学习了 Java 的异常处理机制，发现一些写得很好的博客，转载过来学习。本文转载自: https:&#x2F;&#x2F;www.cnblogs.com&#x2F;lulipro&#x2F;p&#x2F;7504267.html">
<meta property="og:type" content="article">
<meta property="og:title" content="Java异常处理详解">
<meta property="og:url" content="http://yoursite.com/2018/07/10/Java%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8%E5%92%8C%E5%A4%84%E7%90%86%E8%AF%A6%E8%A7%A3/index.html">
<meta property="og:site_name" content="飙戈的博客">
<meta property="og:description" content="之前在学习工作中虽然一直在用 Java 的异常处理，但一直都处于仅仅了解简单用法的表面基础上。最近趁有空进一步深入学习了 Java 的异常处理机制，发现一些写得很好的博客，转载过来学习。本文转载自: https:&#x2F;&#x2F;www.cnblogs.com&#x2F;lulipro&#x2F;p&#x2F;7504267.html">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="http://yoursite.com/.com//exception.png">
<meta property="og:image" content="http://yoursite.com/.com//stack.png">
<meta property="og:image" content="http://yoursite.com/.com//lianshi.png">
<meta property="og:image" content="http://yoursite.com/.com//return.gif">
<meta property="article:published_time" content="2018-07-10T08:52:37.000Z">
<meta property="article:modified_time" content="2023-01-24T07:09:04.024Z">
<meta property="article:author" content="mcbilla">
<meta property="article:tag" content="Java">
<meta property="article:tag" content="异常处理">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="http://yoursite.com/.com//exception.png">

<link rel="canonical" href="http://yoursite.com/2018/07/10/Java%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8%E5%92%8C%E5%A4%84%E7%90%86%E8%AF%A6%E8%A7%A3/">


<script id="page-configurations">
  // https://hexo.io/docs/variables.html
  CONFIG.page = {
    sidebar: "",
    isHome : false,
    isPost : true,
    lang   : 'zh-CN'
  };
</script>

  <title>Java异常处理详解 | 飙戈的博客</title>
  






  <noscript>
  <style>
  .use-motion .brand,
  .use-motion .menu-item,
  .sidebar-inner,
  .use-motion .post-block,
  .use-motion .pagination,
  .use-motion .comments,
  .use-motion .post-header,
  .use-motion .post-body,
  .use-motion .collection-header { opacity: initial; }

  .use-motion .site-title,
  .use-motion .site-subtitle {
    opacity: initial;
    top: initial;
  }

  .use-motion .logo-line-before i { left: initial; }
  .use-motion .logo-line-after i { right: initial; }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage">
  <div class="container use-motion">
    <div class="headband"></div>

    <header class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="切换导航栏">
      <span class="toggle-line toggle-line-first"></span>
      <span class="toggle-line toggle-line-middle"></span>
      <span class="toggle-line toggle-line-last"></span>
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <span class="logo-line-before"><i></i></span>
      <h1 class="site-title">飙戈的博客</h1>
      <span class="logo-line-after"><i></i></span>
    </a>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger">
        <i class="fa fa-search fa-fw fa-lg"></i>
    </div>
  </div>
</div>




<nav class="site-nav">
  <ul id="menu" class="main-menu menu">
        <li class="menu-item menu-item-home">

    <a href="/" rel="section"><i class="fa fa-home fa-fw"></i>首页</a>

  </li>
        <li class="menu-item menu-item-categories">

    <a href="/categories/" rel="section"><i class="fa fa-th fa-fw"></i>分类</a>

  </li>
        <li class="menu-item menu-item-tags">

    <a href="/tags/" rel="section"><i class="fa fa-tags fa-fw"></i>标签</a>

  </li>
        <li class="menu-item menu-item-archives">

    <a href="/archives/" rel="section"><i class="fa fa-archive fa-fw"></i>归档</a>

  </li>
      <li class="menu-item menu-item-search">
        <a role="button" class="popup-trigger"><i class="fa fa-search fa-fw"></i>搜索
        </a>
      </li>
  </ul>
</nav>



  <div class="search-pop-overlay">
    <div class="popup search-popup">
        <div class="search-header">
  <span class="search-icon">
    <i class="fa fa-search"></i>
  </span>
  <div class="search-input-container">
    <input autocomplete="off" autocapitalize="off"
           placeholder="搜索..." spellcheck="false"
           type="search" class="search-input">
  </div>
  <span class="popup-btn-close">
    <i class="fa fa-times-circle"></i>
  </span>
</div>
<div id="search-result">
  <div id="no-result">
    <i class="fa fa-spinner fa-pulse fa-5x fa-fw"></i>
  </div>
</div>

    </div>
  </div>

</div>
    </header>

    
  <div class="back-to-top">
    <i class="fa fa-arrow-up"></i>
    <span>0%</span>
  </div>


    <main class="main">
      <div class="main-inner">
        <div class="content-wrap">
          

          <div class="content post posts-expand">
            

    
  
  
  <article itemscope itemtype="http://schema.org/Article" class="post-block" lang="zh-CN">
    <link itemprop="mainEntityOfPage" href="http://yoursite.com/2018/07/10/Java%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8%E5%92%8C%E5%A4%84%E7%90%86%E8%AF%A6%E8%A7%A3/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/head.jpg">
      <meta itemprop="name" content="mcbilla">
      <meta itemprop="description" content="Constant dropping wears the stone">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="飙戈的博客">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          Java异常处理详解
        </h1>

        <div class="post-meta">
            <span class="post-meta-item">
              <span class="post-meta-item-icon">
                <i class="far fa-calendar"></i>
              </span>
              <span class="post-meta-item-text">发表于</span>

              <time title="创建时间：2018-07-10 16:52:37" itemprop="dateCreated datePublished" datetime="2018-07-10T16:52:37+08:00">2018-07-10</time>
            </span>
              <span class="post-meta-item">
                <span class="post-meta-item-icon">
                  <i class="far fa-calendar-check"></i>
                </span>
                <span class="post-meta-item-text">更新于</span>
                <time title="修改时间：2023-01-24 15:09:04" itemprop="dateModified" datetime="2023-01-24T15:09:04+08:00">2023-01-24</time>
              </span>
            <span class="post-meta-item">
              <span class="post-meta-item-icon">
                <i class="far fa-folder"></i>
              </span>
              <span class="post-meta-item-text">分类于</span>
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/Java/" itemprop="url" rel="index"><span itemprop="name">Java</span></a>
                </span>
                  ，
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/Java/Java%E5%BC%82%E5%B8%B8/" itemprop="url" rel="index"><span itemprop="name">Java异常</span></a>
                </span>
            </span>

          

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">

      
        <blockquote>
<p>之前在学习工作中虽然一直在用 Java 的异常处理，但一直都处于仅仅了解简单用法的表面基础上。最近趁有空进一步深入学习了 Java 的异常处理机制，发现一些写得很好的博客，转载过来学习。本文转载自: <a target="_blank" rel="noopener" href="https://www.cnblogs.com/lulipro/p/7504267.html">https://www.cnblogs.com/lulipro/p/7504267.html</a></p>
</blockquote>
<span id="more"></span>

<h2 id="什么是异常"><a href="#什么是异常" class="headerlink" title="什么是异常"></a>什么是异常</h2><p><em><strong>异常就是程序运行时，发生的不被期望的事件，阻止了程序按照程序员的预期正常执行</strong></em>。Java 为异常提供了优秀的解决办法：异常处理机制。</p>
<p>异常处理机制能让程序在异常发生时，按照代码的预先设定的异常处理逻辑，针对性地处理异常，让程序尽最大可能恢复正常并继续执行，且保持代码的清晰。</p>
<p>Java 中的异常可以是函数中的语句执行时引发的，也可以是程序员通过 throw 语句手动抛出的，只要在 Java 程序中产生了异常，就会用一个对应类型的异常对象来封装异常，JRE就会试图寻找异常处理程序来处理异常。</p>
<h2 id="Java异常的分类和类结构图"><a href="#Java异常的分类和类结构图" class="headerlink" title="Java异常的分类和类结构图"></a>Java异常的分类和类结构图</h2><p>Throwable 类是 Java 异常类型的顶层父类，一个对象只有是 Throwable 类的（直接或者间接）实例，他才是一个异常对象，才能被异常处理机制识别。JDK中内建了一些常用的异常类，我们也可以自定义异常。</p>
<p>Throwable 又派生出 Error 类和 Exception 类。</p>
<ul>
<li><p><strong>Error</strong>：Error 类以及他的子类的实例，代表了 JVM 本身的错误。错误不能被程序员通过代码处理，Error 很少出现。因此，程序员应该关注 Exception 为父类的分支下的各种异常类。</p>
</li>
<li><p><strong>Exception</strong>：Exception 以及他的子类，代表程序运行时发送的各种不期望发生的事件。可以被 Java 异常处理机制使用，是异常处理的核心。</p>
</li>
</ul>
<p><img src="/.com//exception.png" alt="exception"></p>
<p>根据编译器 Javac 对异常的处理要求（注意是分类是给 javac 识别的），将异常类分为2类。</p>
<ul>
<li><p><strong>非检查异常</strong>（unckecked exception）：<em><strong>Error 和 RuntimeException 以及他们的子类</strong></em>。javac在编译时，不会提示和发现这样的异常，不要求在程序处理这些异常。所以如果愿意，我们可以编写代码处理（使用try…catch…finally）这样的异常，也可以不处理。<em><strong>对于这些异常，我们应该修正代码，而不是去通过异常处理器处理</strong></em>。这样的异常发生的原因多半是代码写的有问题。如除0错误 ArithmeticException，错误的强制类型转换错误 ClassCastException，数组索引越界 ArrayIndexOutOfBoundsException，使用了空对象 NullPointerException等等。</p>
</li>
<li><p><strong>检查异常</strong>（checked exception）：<em><strong>除了 Error 和 RuntimeException的其它异常</strong></em>。javac强制要求程序员为这样的异常做预备处理工作。<em><strong>在方法中要么用 try-catch 语句捕获它并处理，要么用 throws 子句声明抛出它，否则编译不会通过</strong></em>。这样的异常一般是由程序的运行环境导致的。因为程序可能被运行在各种未知的环境下，而程序员无法干预用户如何使用他编写的程序，于是程序员就应该为这样的异常时刻准备着。如SQLException , IOException,ClassNotFoundException 等。</p>
</li>
</ul>
<p>下面的代码会演示2个异常类型：ArithmeticException 和 InputMismatchException。前者由于整数除0引发，后者是输入的数据不能被转换为int类型引发。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br></pre></td><td class="code"><pre><span class="line">package com.example;</span><br><span class="line">import java. util .Scanner ;</span><br><span class="line">public class AllDemo</span><br><span class="line">&#123;</span><br><span class="line">      public static void main (String [] args )</span><br><span class="line">      &#123;</span><br><span class="line">            System . out. println( &quot;----欢迎使用命令行除法计算器----&quot; ) ;</span><br><span class="line">            CMDCalculate ();</span><br><span class="line">      &#125;</span><br><span class="line">      public static void CMDCalculate ()</span><br><span class="line">      &#123;</span><br><span class="line">            Scanner scan = new Scanner ( System. in );</span><br><span class="line">            int num1 = scan .nextInt () ;</span><br><span class="line">            int num2 = scan .nextInt () ;</span><br><span class="line">            int result = devide (num1 , num2 ) ;</span><br><span class="line">            System . out. println( &quot;result:&quot; + result) ;</span><br><span class="line">            scan .close () ;</span><br><span class="line">      &#125;</span><br><span class="line">      public static int devide (int num1, int num2 )&#123;</span><br><span class="line">            return num1 / num2 ;</span><br><span class="line">      &#125;</span><br><span class="line">&#125;</span><br><span class="line">/*****************************************</span><br><span class="line"></span><br><span class="line">----欢迎使用命令行除法计算器----</span><br><span class="line">0</span><br><span class="line">Exception in thread &quot;main&quot; java.lang.ArithmeticException : / by zero</span><br><span class="line">     at com.example.AllDemo.devide( AllDemo.java:30 )</span><br><span class="line">     at com.example.AllDemo.CMDCalculate( AllDemo.java:22 )</span><br><span class="line">     at com.example.AllDemo.main( AllDemo.java:12 )</span><br><span class="line"></span><br><span class="line">----欢迎使用命令行除法计算器----</span><br><span class="line">r</span><br><span class="line">Exception in thread &quot;main&quot; java.util.InputMismatchException</span><br><span class="line">     at java.util.Scanner.throwFor( Scanner.java:864 )</span><br><span class="line">     at java.util.Scanner.next( Scanner.java:1485 )</span><br><span class="line">     at java.util.Scanner.nextInt( Scanner.java:2117 )</span><br><span class="line">     at java.util.Scanner.nextInt( Scanner.java:2076 )</span><br><span class="line">     at com.example.AllDemo.CMDCalculate( AllDemo.java:20 )</span><br><span class="line">     at com.example.AllDemo.main( AllDemo.java:12 )</span><br><span class="line">*****************************************/</span><br></pre></td></tr></table></figure>

<p>异常是在执行某个函数时引发的，而函数又是层级调用，形成调用栈的，因为，只要一个函数发生了异常，那么他的所有的caller都会被异常影响。当这些被影响的函数以异常信息输出时，就形成的了 <strong>异常追踪栈</strong>。</p>
<p>异常最先发生的地方，叫做 <strong>异常抛出点</strong>。</p>
<p><img src="/.com//stack.png" alt="stack"></p>
<p>从上面的例子可以看出，当devide函数发生除0异常时，devide函数将抛出ArithmeticException异常，因此调用他的CMDCalculate函数也无法正常完成，因此也发送异常，而CMDCalculate的caller——main 因为CMDCalculate抛出异常，也发生了异常，这样一直向调用栈的栈底回溯。这种行为叫做 <strong>异常的冒泡</strong>，异常的冒泡是为了在当前发生异常的函数或者这个函数的caller中找到最近的异常处理程序。由于这个例子中没有使用任何异常处理机制，因此异常最终由main函数抛给JRE，导致程序终止。</p>
<p>上面的代码不使用异常处理机制，也可以顺利编译，因为2个异常都是非检查异常。但是下面的例子就必须使用异常处理机制，因为异常是检查异常。</p>
<p>代码中我选择使用throws声明异常，让函数的调用者去处理可能发生的异常。但是为什么只throws了IOException呢？因为FileNotFoundException是IOException的子类，在处理范围内。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">@Test</span><br><span class="line">public void testException() throws IOException</span><br><span class="line">&#123;</span><br><span class="line">    //FileInputStream的构造函数会抛出FileNotFoundException</span><br><span class="line">    FileInputStream fileIn = new FileInputStream(&quot;E:\\a.txt&quot;);</span><br><span class="line"></span><br><span class="line">    int word;</span><br><span class="line">    //read方法会抛出IOException</span><br><span class="line">    while((word =  fileIn.read())!=-1)</span><br><span class="line">    &#123;</span><br><span class="line">        System.out.print((char)word);</span><br><span class="line">    &#125;</span><br><span class="line">    //close方法会抛出IOException</span><br><span class="line">    fileIn.clos</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="怎么处理异常"><a href="#怎么处理异常" class="headerlink" title="怎么处理异常"></a>怎么处理异常</h2><p>在编写代码处理异常时，对于检查异常，有2种不同的处理方式：</p>
<ol>
<li>使用 <strong>try…catch…finally</strong> 语句块处理它。</li>
<li>在函数签名中使用 <strong>throws 声明</strong> 交给函数调用者 caller 去解决。</li>
</ol>
<h3 id="try…catch…finally语句块"><a href="#try…catch…finally语句块" class="headerlink" title="try…catch…finally语句块"></a>try…catch…finally语句块</h3><figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line">try&#123;</span><br><span class="line">     //try块中放可能发生异常的代码。</span><br><span class="line">     //如果执行完try且不发生异常，则接着去执行finally块和finally后面的代码（如果有的话）。</span><br><span class="line">     //如果发生异常，则尝试去匹配catch块。</span><br><span class="line"></span><br><span class="line">&#125;catch(SQLException SQLexception)&#123;</span><br><span class="line">    //每一个catch块用于捕获并处理一个特定的异常，或者这异常类型的子类。Java7中可以将多个异常声明在一个catch中。</span><br><span class="line">    //catch后面的括号定义了异常类型和异常参数。如果异常与之匹配且是最先匹配到的，则虚拟机将使用这个catch块来处理异常。</span><br><span class="line">    //在catch块中可以使用这个块的异常参数来获取异常的相关信息。异常参数是这个catch块中的局部变量，其它块不能访问。</span><br><span class="line">    //如果当前try块中发生的异常在后续的所有catch中都没捕获到，则先去执行finally，然后到这个函数的外部caller中去匹配异常处理器。</span><br><span class="line">    //如果try中没有发生异常，则所有的catch块将被忽略。</span><br><span class="line"></span><br><span class="line">&#125;catch(Exception exception)&#123;</span><br><span class="line">    //...</span><br><span class="line">&#125;finally&#123;</span><br><span class="line"></span><br><span class="line">    //finally块通常是可选的。</span><br><span class="line">   //无论异常是否发生，异常是否匹配被处理，finally都会执行。</span><br><span class="line">   //一个try至少要有一个catch块，否则， 至少要有1个finally块。但是finally不是用来处理异常的，finally不会捕获异常。</span><br><span class="line">  //finally主要做一些清理工作，如流的关闭，数据库连接的关闭等。</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>需要注意的地方：</p>
<ol>
<li><p>try块中的局部变量和catch块中的局部变量（包括异常变量），以及finally中的局部变量，他们之间不可共享使用。</p>
</li>
<li><p>每一个catch块用于处理一个异常。异常匹配是按照catch块的顺序从上往下寻找的，只有第一个匹配的catch会得到执行。匹配时，不仅运行精确匹配，也支持父类匹配，因此，<em><strong>如果同一个try块下的多个catch异常类型有父子关系，应该将子类异常放在前面，父类异常放在后面</strong></em>，这样保证每个catch块都有存在的意义。</p>
</li>
<li><p>java中，异常处理的任务就是将执行控制流从异常发生的地方转移到能够处理这种异常的地方去。也就是说：当一个函数的某条语句发生异常时，这条语句的后面的语句不会再执行，它失去了焦点。执行流跳转到最近的匹配的异常处理catch代码块去执行，异常被处理完后，执行流会接着在“处理了这个异常的catch代码块”后面接着执行。</p>
</li>
</ol>
 <figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">public static void main(String[] args)&#123;</span><br><span class="line">        try &#123;</span><br><span class="line">            foo();</span><br><span class="line">        &#125;catch(ArithmeticException ae) &#123;</span><br><span class="line">            System.out.println(&quot;处理异常&quot;);</span><br><span class="line">        &#125;</span><br><span class="line">&#125;</span><br><span class="line">public static void foo()&#123;</span><br><span class="line">        int a = 5/0;  //异常抛出点</span><br><span class="line">        System.out.println(&quot;为什么还不给我涨工资!!!&quot;);  //这里后面不会执行</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<blockquote>
<p>有的编程语言当异常被处理后，控制流会恢复到异常抛出点接着执行，这种策略叫做：恢复式异常处理模式（resumption model of exception handling）<br> 而Java则是让执行流恢复到处理了异常的catch块后接着执行，这种策略叫做：终结式异常处理模式（termination model of exception handling）</p>
</blockquote>
<h3 id="throws-函数声明"><a href="#throws-函数声明" class="headerlink" title="throws 函数声明"></a>throws 函数声明</h3><p>throws声明：如果一个方法内部的代码会抛出检查异常（checked exception），而方法自己又没有完全处理掉，则javac保证你必须在方法的签名上使用throws关键字声明这些可能抛出的异常，否则编译不通过。</p>
<p>throws是另一种处理异常的方式，它不同于try…catch…finally，throws仅仅是将函数中可能出现的异常向调用者声明，而自己则不具体处理。</p>
<p>采取这种异常处理的原因可能是：方法本身不知道如何处理这样的异常，或者说让调用者处理更好，调用者需要为可能发生的异常负责。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">public void foo() throws ExceptionType1 , ExceptionType2 ,ExceptionTypeN</span><br><span class="line">&#123;</span><br><span class="line">     //foo内部可以抛出 ExceptionType1 , ExceptionType2 ,ExceptionTypeN 类的异常，或者他们的子类的异常对象。</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="异常的链化"><a href="#异常的链化" class="headerlink" title="异常的链化"></a>异常的链化</h2><p>在一些大型的，模块化的软件开发中，一旦一个地方发生异常，则如骨牌效应一样，将导致一连串的异常。假设B模块完成自己的逻辑需要调用A模块的方法，如果A模块发生异常，则B也将不能完成而发生异常，但是B在抛出异常时，会将A的异常信息掩盖掉，这将使得异常的根源信息丢失。异常的链化可以将多个模块的异常串联起来，使得异常信息不会丢失。</p>
<p>异常链化: <em>以一个异常对象为参数构造新的异常对象。新的异对象将包含先前异常的信息</em>。这项技术主要是异常类的一个带Throwable参数的函数来实现的。这个当做参数的异常，我们叫他根源异常（cause）。</p>
<p>查看Throwable类源码，可以发现里面有一个Throwable字段cause，就是它保存了构造时传递的根源异常参数。<em>这种设计和链表的结点类设计如出一辙</em>，因此形成链也是自然的了。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line">public class Throwable implements Serializable &#123;</span><br><span class="line">    private Throwable cause = this;</span><br><span class="line"></span><br><span class="line">    public Throwable(String message, Throwable cause) &#123;</span><br><span class="line">        fillInStackTrace();</span><br><span class="line">        detailMessage = message;</span><br><span class="line">        this.cause = cause;</span><br><span class="line">    &#125;</span><br><span class="line">     public Throwable(Throwable cause) &#123;</span><br><span class="line">        fillInStackTrace();</span><br><span class="line">        detailMessage = (cause==null ? null : cause.toString());</span><br><span class="line">        this.cause = cause;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    //........</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>下面是一个例子，演示了异常的链化：从命令行输入2个int，将他们相加，输出。输入的数不是int，则导致getInputNumbers异常，从而导致add函数异常，则可以在add函数中抛出</p>
<p>一个链化的异常。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br></pre></td><td class="code"><pre><span class="line">public static void main(String[] args)</span><br><span class="line">&#123;</span><br><span class="line"></span><br><span class="line">    System.out.println(&quot;请输入2个加数&quot;);</span><br><span class="line">    int result;</span><br><span class="line">    try</span><br><span class="line">    &#123;</span><br><span class="line">        result = add();</span><br><span class="line">        System.out.println(&quot;结果:&quot;+result);</span><br><span class="line">    &#125; catch (Exception e)&#123;</span><br><span class="line">        e.printStackTrace();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">//获取输入的2个整数返回</span><br><span class="line">private static List&lt;Integer&gt; getInputNumbers()</span><br><span class="line">&#123;</span><br><span class="line">    List&lt;Integer&gt; nums = new ArrayList&lt;&gt;();</span><br><span class="line">    Scanner scan = new Scanner(System.in);</span><br><span class="line">    try &#123;</span><br><span class="line">        int num1 = scan.nextInt();</span><br><span class="line">        int num2 = scan.nextInt();</span><br><span class="line">        nums.add(new Integer(num1));</span><br><span class="line">        nums.add(new Integer(num2));</span><br><span class="line">    &#125;catch(InputMismatchException immExp)&#123;</span><br><span class="line">        throw immExp;</span><br><span class="line">    &#125;finally &#123;</span><br><span class="line">        scan.close();</span><br><span class="line">    &#125;</span><br><span class="line">    return nums;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">//执行加法计算</span><br><span class="line">private static int add() throws Exception</span><br><span class="line">&#123;</span><br><span class="line">    int result;</span><br><span class="line">    try &#123;</span><br><span class="line">        List&lt;Integer&gt; nums =getInputNumbers();</span><br><span class="line">        result = nums.get(0)  + nums.get(1);</span><br><span class="line">    &#125;catch(InputMismatchException immExp)&#123;</span><br><span class="line">        throw new Exception(&quot;计算失败&quot;,immExp);  /////////////////////////////链化:以一个异常对象为参数构造新的异常对象。</span><br><span class="line">    &#125;</span><br><span class="line">    return  result;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">/*</span><br><span class="line">请输入2个加数</span><br><span class="line">r 1</span><br><span class="line">java.lang.Exception: 计算失败</span><br><span class="line">    at practise.ExceptionTest.add(ExceptionTest.java:53)</span><br><span class="line">    at practise.ExceptionTest.main(ExceptionTest.java:18)</span><br><span class="line">Caused by: java.util.InputMismatchException</span><br><span class="line">    at java.util.Scanner.throwFor(Scanner.java:864)</span><br><span class="line">    at java.util.Scanner.next(Scanner.java:1485)</span><br><span class="line">    at java.util.Scanner.nextInt(Scanner.java:2117)</span><br><span class="line">    at java.util.Scanner.nextInt(Scanner.java:2076)</span><br><span class="line">    at practise.ExceptionTest.getInputNumbers(ExceptionTest.java:30)</span><br><span class="line">    at practise.ExceptionTest.add(ExceptionTest.java:48)</span><br><span class="line">    ... 1 more</span><br><span class="line"></span><br><span class="line">*/</span><br></pre></td></tr></table></figure>

<p><img src="/.com//lianshi.png" alt="lianshi"></p>
<h2 id="自定义异常"><a href="#自定义异常" class="headerlink" title="自定义异常"></a>自定义异常</h2><p>如果要自定义异常类，则扩展Exception类即可，因此这样的自定义异常都属于检查异常（checked exception）。如果要自定义非检查异常，则扩展自RuntimeException。</p>
<p>按照国际惯例，自定义的异常应该总是包含如下的构造函数：</p>
<ul>
<li>一个无参构造函数</li>
<li>一个带有String参数的构造函数，并传递给父类的构造函数。</li>
<li>一个带有String参数和Throwable参数，并都传递给父类构造函数</li>
<li>一个带有Throwable 参数的构造函数，并传递给父类的构造函数。</li>
</ul>
<p>下面是IOException类的完整源代码，可以借鉴。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line">public class IOException extends Exception</span><br><span class="line">&#123;</span><br><span class="line">    static final long serialVersionUID = 7818375828146090155L;</span><br><span class="line"></span><br><span class="line">    public IOException()</span><br><span class="line">    &#123;</span><br><span class="line">        super();</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    public IOException(String message)</span><br><span class="line">    &#123;</span><br><span class="line">        super(message);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    public IOException(String message, Throwable cause)</span><br><span class="line">    &#123;</span><br><span class="line">        super(message, cause);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    public IOException(Throwable cause)</span><br><span class="line">    &#123;</span><br><span class="line">        super(cause);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h2 id="异常的注意事项"><a href="#异常的注意事项" class="headerlink" title="异常的注意事项"></a>异常的注意事项</h2><h3 id="重写带-throws-声明的父类方法"><a href="#重写带-throws-声明的父类方法" class="headerlink" title="重写带 throws 声明的父类方法"></a>重写带 throws 声明的父类方法</h3><p>当子类重写父类的带有 throws 声明的函数时，其 throws 声明的异常必须在父类异常的可控范围内。意思是说</p>
<ul>
<li>子类 throws 的异常数量不能多于父类</li>
<li>子类 throws 的类型必须是父类异常类型或其子类</li>
</ul>
<p>例如，父类方法 throws 2 个异常，子类就不能 throws 3 个及以上的异常。父类 throws IOException，子类就必须 throws IOException 或者 IOException 的子类。</p>
<p>这是为了支持多态。看下面这个例子</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br></pre></td><td class="code"><pre><span class="line">class Father</span><br><span class="line">&#123;</span><br><span class="line">    public void start() throws IOException</span><br><span class="line">    &#123;</span><br><span class="line">        throw new IOException();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">class Son extends Father</span><br><span class="line">&#123;</span><br><span class="line">    public void start() throws Exception</span><br><span class="line">    &#123;</span><br><span class="line">        throw new SQLException();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">/**********************假设上面的代码是允许的（实质是错误的）***********************/</span><br><span class="line">class Test</span><br><span class="line">&#123;</span><br><span class="line">    public static void main(String[] args)</span><br><span class="line">    &#123;</span><br><span class="line">        Father[] objs = new Father[2];</span><br><span class="line">        objs[0] = new Father();</span><br><span class="line">        objs[1] = new Son();</span><br><span class="line"></span><br><span class="line">        for(Father obj:objs)</span><br><span class="line">        &#123;</span><br><span class="line">        //因为Son类抛出的实质是SQLException，而IOException无法处理它。</span><br><span class="line">        //那么这里的try。。catch就不能处理Son中的异常。</span><br><span class="line">        //多态就不能实现了。</span><br><span class="line">            try &#123;</span><br><span class="line">                 obj.start();</span><br><span class="line">            &#125;catch(IOException)</span><br><span class="line">            &#123;</span><br><span class="line">                 //处理IOException</span><br><span class="line">            &#125;</span><br><span class="line">         &#125;</span><br><span class="line">   &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="异常是线程独立的"><a href="#异常是线程独立的" class="headerlink" title="异常是线程独立的"></a>异常是线程独立的</h3><p>Java 程序可以是多线程的。每一个线程都是一个独立的执行流，独立的函数调用栈。如果程序只有一个线程，那么没有被任何代码处理的异常会导致程序终止。如果是多线程的，那么没有被任何代码处理的异常仅仅会导致异常所在的线程结束。</p>
<p>也就是说，Java中的异常是线程独立的，线程的问题应该由线程自己来解决，而不要委托到外部，也不会直接影响到其它线程的执行。</p>
<h3 id="finally-执行不受-try-块中的-return-影响"><a href="#finally-执行不受-try-块中的-return-影响" class="headerlink" title="finally 执行不受 try 块中的 return 影响"></a>finally 执行不受 try 块中的 return 影响</h3><p>在 try 块中即便有 return，break，continue 等改变执行流的语句，finally 也会执行。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line">public static void main(String[] args)</span><br><span class="line">&#123;</span><br><span class="line">    int re = bar();</span><br><span class="line">    System.out.println(re);</span><br><span class="line">&#125;</span><br><span class="line">private static int bar()</span><br><span class="line">&#123;</span><br><span class="line">    try&#123;</span><br><span class="line">        return 5;</span><br><span class="line">    &#125; finally&#123;</span><br><span class="line">        System.out.println(&quot;finally&quot;);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">/*输出：</span><br><span class="line">finally</span><br><span class="line">5</span><br><span class="line">*/</span><br></pre></td></tr></table></figure>

<p>很多人面对这个问题时，总是在归纳执行的顺序和规律，不过我觉得还是很难理解。我自己总结了一个方法。用如下GIF图说明。</p>
<p><img src="/.com//return.gif" alt="return"></p>
<p>也就是说：try…catch…finally中的return 只要能执行，就都执行了，他们共同向同一个内存地址（假设地址是0x80）写入返回值，后执行的将覆盖先执行的数据，而真正被调用者取的返回值就是最后一次写入的。那么，按照这个思想，下面的这个例子也就不难理解了。</p>
<h3 id="finally-中的-return-会覆盖-try-或者-catch-中的返回值。"><a href="#finally-中的-return-会覆盖-try-或者-catch-中的返回值。" class="headerlink" title="finally 中的 return 会覆盖 try 或者 catch 中的返回值。"></a>finally 中的 return 会覆盖 try 或者 catch 中的返回值。</h3><p>不管 try 和 catch 里面 return 什么值，都会被 finally 的 return 值所覆盖。</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br></pre></td><td class="code"><pre><span class="line">public static void main(String[] args) &#123;</span><br><span class="line">    int result;</span><br><span class="line"></span><br><span class="line">    result = foo();</span><br><span class="line">    System.out.println(result);</span><br><span class="line"></span><br><span class="line">    result = bar();</span><br><span class="line">    System.out.println(result);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">@SuppressWarnings(&quot;finally&quot;)</span><br><span class="line">public static int foo() &#123;</span><br><span class="line">    try &#123;</span><br><span class="line">        int a = 5 / 0;</span><br><span class="line">    &#125; catch (Exception e) &#123;</span><br><span class="line">        return 1;</span><br><span class="line">    &#125; finally &#123;</span><br><span class="line">        return 2;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">@SuppressWarnings(&quot;finally&quot;)</span><br><span class="line">public static int bar() &#123;</span><br><span class="line">    try &#123;</span><br><span class="line">        return 1;</span><br><span class="line">    &#125; finally &#123;</span><br><span class="line">        return 2;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">/*</span><br><span class="line">最终输入结果</span><br><span class="line">2</span><br><span class="line">2</span><br><span class="line"> */</span><br></pre></td></tr></table></figure>

<h3 id="finally-中的-return-会抑制（消灭）前面-try-或者-catch-块中的异常"><a href="#finally-中的-return-会抑制（消灭）前面-try-或者-catch-块中的异常" class="headerlink" title="finally 中的 return 会抑制（消灭）前面 try 或者 catch 块中的异常"></a>finally 中的 return 会抑制（消灭）前面 try 或者 catch 块中的异常</h3><figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br></pre></td><td class="code"><pre><span class="line">public static void main(String[] args)</span><br><span class="line">&#123;</span><br><span class="line">    int result;</span><br><span class="line">    try&#123;</span><br><span class="line">        result = foo();</span><br><span class="line">        System.out.println(result);</span><br><span class="line">    &#125; catch (Exception e)&#123;</span><br><span class="line">        System.out.println(e.getMessage()); //没有捕捉到异常</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    try&#123;</span><br><span class="line">        result  = bar();</span><br><span class="line">        System.out.println(result);</span><br><span class="line">    &#125; catch (Exception e)&#123;</span><br><span class="line">        System.out.println(e.getMessage()); //没有捕捉到异常</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">//catch中的异常被抑制</span><br><span class="line">@SuppressWarnings(&quot;finally&quot;)</span><br><span class="line">public static int foo() throws Exception</span><br><span class="line">&#123;</span><br><span class="line">    try &#123;</span><br><span class="line">        int a = 5/0;</span><br><span class="line">        return 1;</span><br><span class="line">    &#125;catch(ArithmeticException amExp) &#123;</span><br><span class="line">        throw new Exception(&quot;我将被忽略，因为下面的finally中使用了return&quot;);</span><br><span class="line">    &#125;finally &#123;</span><br><span class="line">        return 100;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">//try中的异常被抑制</span><br><span class="line">@SuppressWarnings(&quot;finally&quot;)</span><br><span class="line">public static int bar() throws Exception</span><br><span class="line">&#123;</span><br><span class="line">    try &#123;</span><br><span class="line">        int a = 5/0;</span><br><span class="line">        return 1;</span><br><span class="line">    &#125;finally &#123;</span><br><span class="line">        return 100;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">/*</span><br><span class="line">最终输出：</span><br><span class="line">100</span><br><span class="line">100</span><br><span class="line">*/</span><br></pre></td></tr></table></figure>

<h3 id="finally-中的异常会覆盖（消灭）前面-try-或者-catch-中的异常"><a href="#finally-中的异常会覆盖（消灭）前面-try-或者-catch-中的异常" class="headerlink" title="finally 中的异常会覆盖（消灭）前面 try 或者 catch 中的异常"></a>finally 中的异常会覆盖（消灭）前面 try 或者 catch 中的异常</h3><figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br></pre></td><td class="code"><pre><span class="line">public static void main(String[] args)</span><br><span class="line">&#123;</span><br><span class="line">    int result;</span><br><span class="line">    try&#123;</span><br><span class="line">        result = foo();</span><br><span class="line">    &#125; catch (Exception e)&#123;</span><br><span class="line">        System.out.println(e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">    try&#123;</span><br><span class="line">        result  = bar();</span><br><span class="line">    &#125; catch (Exception e)&#123;</span><br><span class="line">        System.out.println(e.getMessage());</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">//catch中的异常被抑制</span><br><span class="line">@SuppressWarnings(&quot;finally&quot;)</span><br><span class="line">public static int foo() throws Exception</span><br><span class="line">&#123;</span><br><span class="line">    try &#123;</span><br><span class="line">        int a = 5/0;</span><br><span class="line">        return 1;</span><br><span class="line">    &#125;catch(ArithmeticException amExp) &#123;</span><br><span class="line">        throw new Exception(&quot;我将被忽略，因为下面的finally中抛出了新的异常&quot;);</span><br><span class="line">    &#125;finally &#123;</span><br><span class="line">        throw new Exception(&quot;我是finaly中的Exception，覆盖了catch的异常&quot;);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">//try中的异常被抑制</span><br><span class="line">@SuppressWarnings(&quot;finally&quot;)</span><br><span class="line">public static int bar() throws Exception</span><br><span class="line">&#123;</span><br><span class="line">    try &#123;</span><br><span class="line">        int a = 5/0; //这里产生的异常被下面finally抛出的异常覆盖</span><br><span class="line">        return 1;</span><br><span class="line">    &#125;finally &#123;</span><br><span class="line">        throw new Exception(&quot;我是finaly中的Exception，覆盖了try的异常&quot;);</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line">/*</span><br><span class="line">最终输出：</span><br><span class="line">我是finaly中的Exception，覆盖了catch的异常</span><br><span class="line">我是finaly中的Exception，覆盖了try的异常</span><br><span class="line"> */</span><br></pre></td></tr></table></figure>

<p>上面的3个例子都异于常人的编码思维，因此我建议：</p>
<ul>
<li>不要在fianlly中使用return。</li>
<li>不要在finally中抛出异常。</li>
<li>减轻finally的任务，不要在finally中做一些其它的事情，finally块仅仅用来释放资源是最合适的。</li>
<li>将尽量将所有的return写在函数的最后面，而不是try … catch … finally中。</li>
</ul>

    </div>

    
    
    

      <footer class="post-footer">
          <div class="post-tags">
              <a href="/tags/Java/" rel="tag"># Java</a>
              <a href="/tags/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/" rel="tag"># 异常处理</a>
          </div>

        


        
    <div class="post-nav">
      <div class="post-nav-item">
    <a href="/2018/07/06/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E8%B0%83%E6%95%B4/" rel="prev" title="小程序获取openid、session_key和access_token">
      <i class="fa fa-chevron-left"></i> 小程序获取openid、session_key和access_token
    </a></div>
      <div class="post-nav-item">
    <a href="/2018/07/10/Java%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E4%B8%ADthrow%E5%92%8Cthrows%E7%9A%84%E5%8C%BA%E5%88%AB%E5%92%8C%E7%94%A8%E6%B3%95/" rel="next" title="Java异常处理中throw和throws的区别和用法">
      Java异常处理中throw和throws的区别和用法 <i class="fa fa-chevron-right"></i>
    </a></div>
    </div>
      </footer>
    
  </article>
  
  
  



          </div>
          

<script>
  window.addEventListener('tabs:register', () => {
    let { activeClass } = CONFIG.comments;
    if (CONFIG.comments.storage) {
      activeClass = localStorage.getItem('comments_active') || activeClass;
    }
    if (activeClass) {
      let activeTab = document.querySelector(`a[href="#comment-${activeClass}"]`);
      if (activeTab) {
        activeTab.click();
      }
    }
  });
  if (CONFIG.comments.storage) {
    window.addEventListener('tabs:click', event => {
      if (!event.target.matches('.tabs-comment .tab-content .tab-pane')) return;
      let commentClass = event.target.classList[1];
      localStorage.setItem('comments_active', commentClass);
    });
  }
</script>

        </div>
          
  
  <div class="toggle sidebar-toggle">
    <span class="toggle-line toggle-line-first"></span>
    <span class="toggle-line toggle-line-middle"></span>
    <span class="toggle-line toggle-line-last"></span>
  </div>

  <aside class="sidebar">
    <div class="sidebar-inner">

      <ul class="sidebar-nav motion-element">
        <li class="sidebar-nav-toc">
          文章目录
        </li>
        <li class="sidebar-nav-overview">
          站点概览
        </li>
      </ul>

      <!--noindex-->
      <div class="post-toc-wrap sidebar-panel">
          <div class="post-toc motion-element"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E4%BB%80%E4%B9%88%E6%98%AF%E5%BC%82%E5%B8%B8"><span class="nav-number">1.</span> <span class="nav-text">什么是异常</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#Java%E5%BC%82%E5%B8%B8%E7%9A%84%E5%88%86%E7%B1%BB%E5%92%8C%E7%B1%BB%E7%BB%93%E6%9E%84%E5%9B%BE"><span class="nav-number">2.</span> <span class="nav-text">Java异常的分类和类结构图</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%E5%BC%82%E5%B8%B8"><span class="nav-number">3.</span> <span class="nav-text">怎么处理异常</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#try%E2%80%A6catch%E2%80%A6finally%E8%AF%AD%E5%8F%A5%E5%9D%97"><span class="nav-number">3.1.</span> <span class="nav-text">try…catch…finally语句块</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#throws-%E5%87%BD%E6%95%B0%E5%A3%B0%E6%98%8E"><span class="nav-number">3.2.</span> <span class="nav-text">throws 函数声明</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%BC%82%E5%B8%B8%E7%9A%84%E9%93%BE%E5%8C%96"><span class="nav-number">4.</span> <span class="nav-text">异常的链化</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8"><span class="nav-number">5.</span> <span class="nav-text">自定义异常</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%BC%82%E5%B8%B8%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9"><span class="nav-number">6.</span> <span class="nav-text">异常的注意事项</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#%E9%87%8D%E5%86%99%E5%B8%A6-throws-%E5%A3%B0%E6%98%8E%E7%9A%84%E7%88%B6%E7%B1%BB%E6%96%B9%E6%B3%95"><span class="nav-number">6.1.</span> <span class="nav-text">重写带 throws 声明的父类方法</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#%E5%BC%82%E5%B8%B8%E6%98%AF%E7%BA%BF%E7%A8%8B%E7%8B%AC%E7%AB%8B%E7%9A%84"><span class="nav-number">6.2.</span> <span class="nav-text">异常是线程独立的</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally-%E6%89%A7%E8%A1%8C%E4%B8%8D%E5%8F%97-try-%E5%9D%97%E4%B8%AD%E7%9A%84-return-%E5%BD%B1%E5%93%8D"><span class="nav-number">6.3.</span> <span class="nav-text">finally 执行不受 try 块中的 return 影响</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally-%E4%B8%AD%E7%9A%84-return-%E4%BC%9A%E8%A6%86%E7%9B%96-try-%E6%88%96%E8%80%85-catch-%E4%B8%AD%E7%9A%84%E8%BF%94%E5%9B%9E%E5%80%BC%E3%80%82"><span class="nav-number">6.4.</span> <span class="nav-text">finally 中的 return 会覆盖 try 或者 catch 中的返回值。</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally-%E4%B8%AD%E7%9A%84-return-%E4%BC%9A%E6%8A%91%E5%88%B6%EF%BC%88%E6%B6%88%E7%81%AD%EF%BC%89%E5%89%8D%E9%9D%A2-try-%E6%88%96%E8%80%85-catch-%E5%9D%97%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8"><span class="nav-number">6.5.</span> <span class="nav-text">finally 中的 return 会抑制（消灭）前面 try 或者 catch 块中的异常</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally-%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8%E4%BC%9A%E8%A6%86%E7%9B%96%EF%BC%88%E6%B6%88%E7%81%AD%EF%BC%89%E5%89%8D%E9%9D%A2-try-%E6%88%96%E8%80%85-catch-%E4%B8%AD%E7%9A%84%E5%BC%82%E5%B8%B8"><span class="nav-number">6.6.</span> <span class="nav-text">finally 中的异常会覆盖（消灭）前面 try 或者 catch 中的异常</span></a></li></ol></li></ol></div>
      </div>
      <!--/noindex-->

      <div class="site-overview-wrap sidebar-panel">
        <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
    <img class="site-author-image" itemprop="image" alt="mcbilla"
      src="/images/head.jpg">
  <p class="site-author-name" itemprop="name">mcbilla</p>
  <div class="site-description" itemprop="description">Constant dropping wears the stone</div>
</div>
<div class="site-state-wrap motion-element">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
          <a href="/archives/">
        
          <span class="site-state-item-count">28</span>
          <span class="site-state-item-name">日志</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
            <a href="/categories/">
          
        <span class="site-state-item-count">16</span>
        <span class="site-state-item-name">分类</span></a>
      </div>
      <div class="site-state-item site-state-tags">
            <a href="/tags/">
          
        <span class="site-state-item-count">12</span>
        <span class="site-state-item-name">标签</span></a>
      </div>
  </nav>
</div>
  <div class="links-of-author motion-element">
      <span class="links-of-author-item">
        <a href="https://github.com/mcbilla" title="GitHub → https:&#x2F;&#x2F;github.com&#x2F;mcbilla" rel="noopener" target="_blank"><i class="fab fa-github fa-fw"></i>GitHub</a>
      </span>
  </div>



      </div>

    </div>
  </aside>
  <div id="sidebar-dimmer"></div>


      </div>
    </main>

    <footer class="footer">
      <div class="footer-inner">
        

        

<div class="copyright">
  
  &copy; 
  <span itemprop="copyrightYear">2023</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">mcbilla</span>
</div>
  <div class="powered-by">由 <a href="https://hexo.io/" class="theme-link" rel="noopener" target="_blank">Hexo</a> & <a href="https://mist.theme-next.org/" class="theme-link" rel="noopener" target="_blank">NexT.Mist</a> 强力驱动
  </div>

        








      </div>
    </footer>
  </div>

  
  <script src="/lib/anime.min.js"></script>
  <script src="/lib/velocity/velocity.min.js"></script>
  <script src="/lib/velocity/velocity.ui.min.js"></script>

<script src="/js/utils.js"></script>

<script src="/js/motion.js"></script>


<script src="/js/schemes/muse.js"></script>


<script src="/js/next-boot.js"></script>




  




  
<script src="/js/local-search.js"></script>













  

  

</body>
</html>
